version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=[root_password]
      - MYSQL_PASSWORD=[password]
      - MYSQL_DATABASE=[database]
      - MYSQL_USER=[user]
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - /docker/nextcloud/redis:/data
    restart: unless-stopped

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
      - redis
    volumes:
      - /path/to/config:/var/www/html
      - /path/to/data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=[password]
      - MYSQL_DATABASE=[database]
      - MYSQL_USER=[user]
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=[domain]
      - NEXTCLOUD_ADMIN_USER=[admin_user]
      - NEXTCLOUD_ADMIN_PASSWORD=[admin_password]