name: affine
services:
  affine:
    image: ghcr.io/toeverything/affine:stable
    container_name: affine_server
    ports:
      - '3010:3010'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      # custom configurations
      - /path/to/affine/config:/root/.affine/config
      - /path/to/affine/storage:/root/.affine/storage
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://affine_user:affine_user_password@postgres:5432/affine
      - AFFINE_INDEXER_ENABLED=false
    restart: unless-stopped

  affine_migration:
    image: ghcr.io/toeverything/affine:stable
    container_name: affine_migration_job
    volumes:
      # custom configurations
      - /path/to/affine/config:/root/.affine/config
      - /path/to/affine/storage:/root/.affine/storage
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://affine_user:affine_user_password@postgres:5432/affine
      - AFFINE_INDEXER_ENABLED=false
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis
    container_name: affine_redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    container_name: affine_postgres
    volumes:
      - /path/to/affine/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: affine_user
      POSTGRES_PASSWORD: affine_user_password
      POSTGRES_DB: affine
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # you better set a password for you database
      # or you may add 'POSTGRES_HOST_AUTH_METHOD=trust' to ignore postgres security policy
      # POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', "affine_user", '-d', "affine"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped